package com.tyyagoo.translationmetrics.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Document
@Data
public class TranslationEvent {
    /*
    * Why not use translationId as id?
    * We can't trust that event producers will grant uniqueness of an id
    * So, is better use our "own" id (the id generated by mongo).
     */
    @Id
    private String id;
    private String translationId;
    private LocalDateTime timestamp;
    private String sourceLanguage;
    private String targetLanguage;
    private String clientName;

    private int duration; // in ms
    private int numberOfWords;

    private static String eventName = "translation_delivered";
}
